=== saasan/noreal-koma-json/schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$ref": "#/definitions/MangaItem",
    "definitions": {
        "MangaItem": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "id": {
                    "type": "string",
                    "pattern": "^(https://twitter\\.com/noreal_koma/status/\\d+|https://www\\.instagram\\.com/p/[^/]+/)$"
                },
                "publishDate": {
                    "type": "string",
                    "format": "date-time"
                },
                "text": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "reading": {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "pattern": "^[ぁ-ゖー]*$"
                    }
                },
                "tag": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "series": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "characters": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "suzuri": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/LinkItemSuzuri"
                    }
                },
                "lineSticker": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/LinkItemLineSticker"
                    }
                },
                "instagram": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/LinkItemInstagram"
                    }
                },
                "QRCode": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/LinkItem"
                    }
                }
            },
            "required": [
                "id",
                "publishDate",
                "reading",
                "text",
                "tag",
                "series",
                "characters",
                "suzuri",
                "lineSticker",
                "instagram",
                "QRCode"
            ],
            "title": "MangaItem"
        },
        "LinkItem": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "title": {
                    "type": "string"
                },
                "url": {
                    "type": "string",
                    "pattern": "^https://"
                }
            },
            "required": [
                "title",
                "url"
            ],
            "title": "LinkItem"
        },
        "LinkItemSuzuri": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "title": {
                    "type": "string"
                },
                "url": {
                    "type": "string",
                    "pattern": "^https://suzuri\\.jp/noreal_koma/designs/\\d+$"
                }
            },
            "required": [
                "title",
                "url"
            ],
            "title": "LinkItemSuzuri"
        },
        "LinkItemLineSticker": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "title": {
                    "type": "string"
                },
                "url": {
                    "type": "string",
                    "pattern": "^https://store\\.line\\.me/stickershop/product/\\d+/ja$"
                }
            },
            "required": [
                "title",
                "url"
            ],
            "title": "LinkItemLineSticker"
        },
        "LinkItemInstagram": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "title": {
                    "type": "string"
                },
                "url": {
                    "type": "string",
                    "pattern": "^https://www\\.instagram\\.com/noreal_koma/p/[^/]+/$"
                }
            },
            "required": [
                "title",
                "url"
            ],
            "title": "LinkItemInstagram"
        }
    }
}

=== saasan/noreal-koma-json/202503/noreal_koma-1904843773315514621-01-20250326193200.json
{
    "id": "https://twitter.com/noreal_koma/status/1904843773315514621",
    "publishDate": "2025-03-26T10:32:00+00:00",
    "text": [
        "井伊直弼どこ!?",
        "はやく誅殺しないとヤバいよ!!"
    ],
    "reading": [
        "いいなおすけどこ",
        "はやくちゅうさつしないとやばいよ"
    ],
    "tag": [
        "VR",
        "ゴーグル"
    ],
    "series": [],
    "characters": [],
    "suzuri": [
        {
            "title": "存在しない漫画の１コマ（女）",
            "url": "https://suzuri.jp/noreal_koma/designs/17480798"
        }
    ],
    "lineSticker": [],
    "instagram": [
        {
            "title": "Instagram",
            "url": "https://www.instagram.com/noreal_koma/p/DHqS_ZAySMX/"
        }
    ],
    "QRCode": []
}

=== saasan/noreal-koma-json/202409/noreal_koma-1835265302076035368-01-20240915193200.json
{
    "id": "https://twitter.com/noreal_koma/status/1835265302076035368",
    "publishDate": "2024-09-15T10:32:00+00:00",
    "text": [
        "頼む!!バズってくれ!!",
        "バズれーーっ!!バズれーーっ!!"
    ],
    "reading": [
        "たのむばずってくれ",
        "ばずれーーっばずれーーっ"
    ],
    "tag": [
        "スマートフォン",
        "銃",
        "SNS",
        "裸"
    ],
    "series": [],
    "characters": [],
    "suzuri": [],
    "lineSticker": [],
    "instagram": [
        {
            "title": "Instagram",
            "url": "https://www.instagram.com/noreal_koma/p/DEqy4_dSM9X/"
        }
    ],
    "QRCode": []
}

=== saasan/noreal-koma-json/202508/noreal_koma-1956302850130137516-01-20250815193200.json
{
    "id": "https://twitter.com/noreal_koma/status/1956302850130137516",
    "publishDate": "2025-08-15T10:32:00+00:00",
    "text": [
        "……？",
        "僕何か嫌われることした？",
        "いてて…",
        "……昨日あの子の両親殺したでしょ"
    ],
    "reading": [
        "",
        "ぼくなにかきらわれることした",
        "いてて",
        "きのうあのこのりょうしんころしたでしょ"
    ],
    "tag": [
        "片目隠れ",
        "髪留め",
        "ぱっつん",
        "マント"
    ],
    "series": [],
    "characters": [],
    "suzuri": [],
    "lineSticker": [],
    "instagram": [],
    "QRCode": []
}

=== saasan/noreal-koma-json/202501/noreal_koma-1875852743375466861-01-20250105193200.json
{
    "id": "https://twitter.com/noreal_koma/status/1875852743375466861",
    "publishDate": "2025-01-05T10:32:00+00:00",
    "text": [
        "2人ともご飯できたわよ～",
        "はーい"
    ],
    "reading": [
        "ふたりともごはんできたわよー",
        "はーい"
    ],
    "tag": [
        "障子"
    ],
    "series": [],
    "characters": [],
    "suzuri": [],
    "lineSticker": [],
    "instagram": [],
    "QRCode": []
}

=== saasan/noreal-koma-json/202410/noreal_koma-1850123205178249216-01-20241026193200.json
{
    "id": "https://twitter.com/noreal_koma/status/1850123205178249216",
    "publishDate": "2024-10-26T10:32:00+00:00",
    "text": [
        "うっわ最悪…",
        "なんで私がアンタのを処理しなきゃいけないのよ…",
        "誰がシーツ取ってきてー",
        "最悪なのはこっちよ!!"
    ],
    "reading": [
        "うっわさいあく",
        "なんでわたしがあんたのをしょりしなきゃいけないのよ",
        "だれがしーつとってきてー",
        "さいあくなのはこっちよ"
    ],
    "tag": [
        "ミニキャラ",
        "吹き出しに顔"
    ],
    "series": [],
    "characters": [],
    "suzuri": [],
    "lineSticker": [],
    "instagram": [],
    "QRCode": []
}

=== saasan/noreal-koma-json/202508/noreal_koma-1955940462654640270-01-20250814193200.json
{
    "id": "https://twitter.com/noreal_koma/status/1955940462654640270",
    "publishDate": "2025-08-14T10:32:00+00:00",
    "text": [
        "何せこの俺がこの漫画の主人公だからな！",
        "都まひの…本作の主人公で、群馬女子美術大学一年 ハン・ファン・メーヘレンを崇拝してい"
    ],
    "reading": [
        "なんせこのおれがこのまんがのしゅじんこうだからな",
        "みやこまひのほんさくのしゅじんこうでぐんまじょしびじゅつだいがくいちねんはんふぁんめーへれんをすうはいしてい"
    ],
    "tag": [
        "モヒカン",
        "ヒゲ",
        "ピアス",
        "バーコード"
    ],
    "series": [],
    "characters": [],
    "suzuri": [],
    "lineSticker": [],
    "instagram": [],
    "QRCode": []
}

=== saasan/noreal-koma-json/202502/noreal_koma-1894566580249661728-01-20250226105406.json
{
    "id": "https://twitter.com/noreal_koma/status/1894566580249661728",
    "publishDate": "2025-02-26T01:54:06+00:00",
    "text": [
        "尾張くんと端鞠さん 小柳津由一",
        "デビチル創造の書をクリア！落ち着いたら破壊の書もやりたい～ (由一)",
        "シンケンドゥー 抹茶川らて",
        "短い間でしたがお世話になりました！必ず戻るのでこうご期待!! (らて)"
    ],
    "reading": [
        "おわりくんとはじまりさんおやいづゆいち",
        "でびちるそうぞうのしょをくりあおちついたらはかいのしょもやりたいーゆいち",
        "しんけんどぅーまっちゃがわらて",
        "みじかいあいだでしたがおせわになりましたかならずもどるのでこうごきたいらて"
    ],
    "tag": [
        "雑誌",
        "目次",
        "作者",
        "漫画家",
        "コメント",
        "デビチル"
    ],
    "series": [
        "尾張くんと端鞠さん",
        "シンケンドゥー"
    ],
    "characters": [
        "端鞠万梨子"
    ],
    "suzuri": [],
    "lineSticker": [],
    "instagram": [],
    "QRCode": []
}

=== saasan/noreal-koma-json/202507/noreal_koma-1950142256138326407-01-20250729193200.json
{
    "id": "https://twitter.com/noreal_koma/status/1950142256138326407",
    "publishDate": "2025-07-29T10:32:00+00:00",
    "text": [
        "ははっ いいぞいいぞ",
        "どんどん伸びろ～！"
    ],
    "reading": [
        "ははっいいぞいいぞ",
        "どんどんのびろー"
    ],
    "tag": [
        "鎖",
        "褐色肌",
        "巨乳"
    ],
    "series": [],
    "characters": [],
    "suzuri": [],
    "lineSticker": [],
    "instagram": [],
    "QRCode": []
}
