=== saasan/noreal-koma-json/schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$ref": "#/definitions/MangaItem",
    "definitions": {
        "MangaItem": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "id": {
                    "type": "string",
                    "pattern": "^(https://twitter\\.com/noreal_koma/status/\\d+|https://www\\.instagram\\.com/p/[^/]+/)$"
                },
                "publishDate": {
                    "type": "string",
                    "format": "date-time"
                },
                "text": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "reading": {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "pattern": "^[ぁ-ゖー]*$"
                    }
                },
                "tag": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "series": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "characters": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "suzuri": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/LinkItemSuzuri"
                    }
                },
                "lineSticker": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/LinkItemLineSticker"
                    }
                },
                "instagram": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/LinkItemInstagram"
                    }
                },
                "QRCode": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/LinkItem"
                    }
                }
            },
            "required": [
                "id",
                "publishDate",
                "reading",
                "text",
                "tag",
                "series",
                "characters",
                "suzuri",
                "lineSticker",
                "instagram",
                "QRCode"
            ],
            "title": "MangaItem"
        },
        "LinkItem": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "title": {
                    "type": "string"
                },
                "url": {
                    "type": "string",
                    "pattern": "^https://"
                }
            },
            "required": [
                "title",
                "url"
            ],
            "title": "LinkItem"
        },
        "LinkItemSuzuri": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "title": {
                    "type": "string"
                },
                "url": {
                    "type": "string",
                    "pattern": "^https://suzuri\\.jp/noreal_koma/designs/\\d+$"
                }
            },
            "required": [
                "title",
                "url"
            ],
            "title": "LinkItemSuzuri"
        },
        "LinkItemLineSticker": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "title": {
                    "type": "string"
                },
                "url": {
                    "type": "string",
                    "pattern": "^https://store\\.line\\.me/stickershop/product/\\d+/ja$"
                }
            },
            "required": [
                "title",
                "url"
            ],
            "title": "LinkItemLineSticker"
        },
        "LinkItemInstagram": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "title": {
                    "type": "string"
                },
                "url": {
                    "type": "string",
                    "pattern": "^https://www\\.instagram\\.com/noreal_koma/p/[^/]+/$"
                }
            },
            "required": [
                "title",
                "url"
            ],
            "title": "LinkItemInstagram"
        }
    }
}

=== saasan/noreal-koma-json/202507/noreal_koma-1946155990178746669-01-20250718193200.json
{
    "id": "https://twitter.com/noreal_koma/status/1946155990178746669",
    "publishDate": "2025-07-18T10:32:00+00:00",
    "text": [
        "生きて帰れるんだ!!"
    ],
    "reading": [
        "いきてかえれるんだ"
    ],
    "tag": [
        "体操服",
        "死亡フラグ",
        "巨乳"
    ],
    "series": [],
    "characters": [],
    "suzuri": [],
    "lineSticker": [
        {
            "title": "存在しない漫画のLINEスタンプ 第３弾",
            "url": "https://store.line.me/stickershop/product/31412619/ja"
        }
    ],
    "instagram": [],
    "QRCode": []
}

=== saasan/noreal-koma-json/202507/noreal_koma-1945793602288046137-01-20250717193200.json
{
    "id": "https://twitter.com/noreal_koma/status/1945793602288046137",
    "publishDate": "2025-07-17T10:32:00+00:00",
    "text": [
        "続いて3回戦第2試合は――",
        "因縁(?)の対決だァッ!!",
        "龍子(ロンコ) VS ニセ龍子(ロンコ)"
    ],
    "reading": [
        "つづいてさんかいせんだいにしあいは",
        "いんねんのたいけつだぁっ",
        "ろんこばーさすにせろんこ"
    ],
    "tag": [
        "巨乳",
        "ヒゲ"
    ],
    "series": [],
    "characters": [],
    "suzuri": [],
    "lineSticker": [],
    "instagram": [],
    "QRCode": []
}

=== saasan/noreal-koma-json/202503/noreal_koma-1897958403429020100-01-20250307193200.json
{
    "id": "https://twitter.com/noreal_koma/status/1897958403429020100",
    "publishDate": "2025-03-07T10:32:00+00:00",
    "text": [
        "瘡蓋の中の体毛のように",
        "人知れず成長していたのさ",
        "フー…"
    ],
    "reading": [
        "かさぶたのなかのたいもうのように",
        "ひとしれずせいちょうしていたのさ",
        "ふー"
    ],
    "tag": [
        "スポーツ"
    ],
    "series": [],
    "characters": [],
    "suzuri": [
        {
            "title": "存在しない漫画の１コマ（男）",
            "url": "https://suzuri.jp/noreal_koma/designs/17480388"
        }
    ],
    "lineSticker": [],
    "instagram": [],
    "QRCode": []
}

=== saasan/noreal-koma-json/202502/noreal_koma-1894034115717931194-01-20250224233817.json
{
    "id": "https://twitter.com/noreal_koma/status/1894034115717931194",
    "publishDate": "2025-02-24T14:38:17+00:00",
    "text": [
        "黒々漆子…15年間地下で飲まず食わずだったので食べ物に興味津々。",
        "吹鴫ナユ太…普通の家庭で育った高校 寝相がめちゃくちゃ悪い"
    ],
    "reading": [
        "くろぐろうるこじゅうごねんかんちかでのまずくわすだったのでたべものにきょうみしんしん",
        "ふかしぎなゆたふつうのかていでそだったこうこうねそうがめちゃくちゃわるい"
    ],
    "tag": [
        "雑誌",
        "柱",
        "登場人物紹介"
    ],
    "series": [
        "黒々さん"
    ],
    "characters": [
        "黒々漆子",
        "吹鴫ナユ太"
    ],
    "suzuri": [],
    "lineSticker": [],
    "instagram": [],
    "QRCode": []
}

=== saasan/noreal-koma-json/202506/noreal_koma-1936733905471865015-01-20250622193200.json
{
    "id": "https://twitter.com/noreal_koma/status/1936733905471865015",
    "publishDate": "2025-06-22T10:32:00+00:00",
    "text": [
        "スリ対策用のダミー財布ですわ!!",
        "6000€だけ入れてますの!!",
        "※約100万円",
        "……もうなんでもアリねアンタ"
    ],
    "reading": [
        "すりたいさくようのだみーさいふですわ",
        "ろくせんゆーろだけいれてますの",
        "やくひゃくまんえん",
        "もうなんでもありねあんた"
    ],
    "tag": [
        "ミニキャラ",
        "お嬢様",
        "モン・サン＝ミシェル",
        "フランス"
    ],
    "series": [],
    "characters": [],
    "suzuri": [],
    "lineSticker": [],
    "instagram": [],
    "QRCode": []
}

=== saasan/noreal-koma-json/202505/noreal_koma-1921151226713972928-01-20250510193200.json
{
    "id": "https://twitter.com/noreal_koma/status/1921151226713972928",
    "publishDate": "2025-05-10T10:32:00+00:00",
    "text": [
        "同じく幹部の仲間愛",
        "自らの邪魔になれば仲間すら平気で切り捨てるクズだ",
        "仲間様ー!!",
        "愛さまー♥"
    ],
    "reading": [
        "おなじくかんぶのなかまあい",
        "みずからのじゃまになればなかますらへいきできりすてるくずだ",
        "なかまさま",
        "あいさま"
    ],
    "tag": [
        "巨乳",
        "ホクロ",
        "タートルネック",
        "ノースリーブ"
    ],
    "series": [],
    "characters": [],
    "suzuri": [],
    "lineSticker": [],
    "instagram": [],
    "QRCode": []
}

=== saasan/noreal-koma-json/202504/noreal_koma-1908830039023538207-01-20250406193200.json
{
    "id": "https://twitter.com/noreal_koma/status/1908830039023538207",
    "publishDate": "2025-04-06T10:32:00+00:00",
    "text": [
        "更衣室に仕掛けた超小型カメラは82台……",
        "これなら一度の着替えで男子生徒全員のチンポが見れる!!"
    ],
    "reading": [
        "こういしつにしかけたちょうこがたかめらはだい",
        "これならいちどのきがえでだんしせいとぜんいんのちんぽがみれる"
    ],
    "tag": [
        "変態",
        "盗撮",
        "犯罪者",
        "下ネタ",
        "チンポ",
        "モザイク"
    ],
    "series": [],
    "characters": [],
    "suzuri": [],
    "lineSticker": [],
    "instagram": [],
    "QRCode": []
}

=== saasan/noreal-koma-json/202408/noreal_koma-1829883240196554849-01-20240831230536.json
{
    "id": "https://twitter.com/noreal_koma/status/1829883240196554849",
    "publishDate": "2024-08-31T14:05:36+00:00",
    "text": [],
    "reading": [],
    "tag": [
        "制服",
        "セーラー服"
    ],
    "series": [
        "黒々さん"
    ],
    "characters": [
        "黒々漆子"
    ],
    "suzuri": [],
    "lineSticker": [],
    "instagram": [],
    "QRCode": []
}
