=== saasan/noreal-koma-json/schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$ref": "#/definitions/MangaItem",
    "definitions": {
        "MangaItem": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "id": {
                    "type": "string",
                    "pattern": "^(https://twitter\\.com/noreal_koma/status/\\d+|https://www\\.instagram\\.com/p/[^/]+/)$"
                },
                "publishDate": {
                    "type": "string",
                    "format": "date-time"
                },
                "text": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "reading": {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "pattern": "^[ぁ-ゖー]*$"
                    }
                },
                "tag": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "series": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "characters": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "suzuri": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/LinkItemSuzuri"
                    }
                },
                "lineSticker": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/LinkItemLineSticker"
                    }
                },
                "instagram": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/LinkItemInstagram"
                    }
                },
                "QRCode": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/LinkItem"
                    }
                }
            },
            "required": [
                "id",
                "publishDate",
                "reading",
                "text",
                "tag",
                "series",
                "characters",
                "suzuri",
                "lineSticker",
                "instagram",
                "QRCode"
            ],
            "title": "MangaItem"
        },
        "LinkItem": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "title": {
                    "type": "string"
                },
                "url": {
                    "type": "string",
                    "pattern": "^https://"
                }
            },
            "required": [
                "title",
                "url"
            ],
            "title": "LinkItem"
        },
        "LinkItemSuzuri": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "title": {
                    "type": "string"
                },
                "url": {
                    "type": "string",
                    "pattern": "^https://suzuri\\.jp/noreal_koma/designs/\\d+$"
                }
            },
            "required": [
                "title",
                "url"
            ],
            "title": "LinkItemSuzuri"
        },
        "LinkItemLineSticker": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "title": {
                    "type": "string"
                },
                "url": {
                    "type": "string",
                    "pattern": "^https://store\\.line\\.me/stickershop/product/\\d+/ja$"
                }
            },
            "required": [
                "title",
                "url"
            ],
            "title": "LinkItemLineSticker"
        },
        "LinkItemInstagram": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "title": {
                    "type": "string"
                },
                "url": {
                    "type": "string",
                    "pattern": "^https://www\\.instagram\\.com/noreal_koma/p/[^/]+/$"
                }
            },
            "required": [
                "title",
                "url"
            ],
            "title": "LinkItemInstagram"
        }
    }
}

=== saasan/noreal-koma-json/202411/noreal_koma-1858820513772290093-01-20241119193200.json
{
    "id": "https://twitter.com/noreal_koma/status/1858820513772290093",
    "publishDate": "2024-11-19T10:32:00+00:00",
    "text": [
        "出やがったな……!!",
        "偉業の生命体!!"
    ],
    "reading": [
        "でやがったな",
        "いぎょうのせいめいたい"
    ],
    "tag": [
        "武器",
        "単行本修正",
        "傷跡"
    ],
    "series": [],
    "characters": [],
    "suzuri": [
        {
            "title": "存在しない漫画の１コマ（男）",
            "url": "https://suzuri.jp/noreal_koma/designs/17480388"
        }
    ],
    "lineSticker": [],
    "instagram": [],
    "QRCode": []
}

=== saasan/noreal-koma-json/202505/noreal_koma-1923687941852811594-01-20250517190301.json
{
    "id": "https://www.instagram.com/p/DJwCixwSaDb/",
    "publishDate": "2025-05-17T10:03:01+00:00",
    "text": [
        "こうなったらフォロワーさんに訊いちゃうもんね♪",
        "えーっと……「オススメのオスターピンツェン専門店教えてください」…っと♪"
    ],
    "reading": [
        "こうなったらふぉろわーさんにきいちゃうもんね",
        "えーっとおすすめのおすたーぴんつぇんせんもんてんおしえてくださいっと"
    ],
    "tag": [
        "髪留め",
        "スマートフォン",
        "パジャマ",
        "SNS"
    ],
    "series": [],
    "characters": [],
    "suzuri": [],
    "lineSticker": [],
    "instagram": [],
    "QRCode": []
}

=== saasan/noreal-koma-json/202507/noreal_koma-1947605541062365556-01-20250722193200.json
{
    "id": "https://twitter.com/noreal_koma/status/1947605541062365556",
    "publishDate": "2025-07-22T10:32:00+00:00",
    "text": [
        "俺はあの時……奴に復讐を誓ったんだ…!!",
        "時は遡り……",
        "弥生時代"
    ],
    "reading": [
        "おれはあのときやつにふくしゅうをちかったんだ",
        "ときはさかのぼり",
        "やよいじだい"
    ],
    "tag": [
        "ホクロ",
        "フード"
    ],
    "series": [],
    "characters": [],
    "suzuri": [],
    "lineSticker": [],
    "instagram": [],
    "QRCode": []
}

=== saasan/noreal-koma-json/202507/noreal_koma-1942894498838634516-01-20250709193200.json
{
    "id": "https://twitter.com/noreal_koma/status/1942894498838634516",
    "publishDate": "2025-07-09T10:32:00+00:00",
    "text": [
        "一日中こっくりさんのことを考えて過ごしてる所謂〝こっくりバカ〟だ",
        "元素の周期表を改造してこっくりボードにできないかな……",
        "な？"
    ],
    "reading": [
        "いちにちじゅうこっくりさんのことをかんがえてすごしてるいわゆるこっくりばかだ",
        "げんそのしゅうきひょうをかいぞうしてこっくりぼーどにできないかな",
        "な"
    ],
    "tag": [
        "制服",
        "セーラー服",
        "巨乳",
        "髪留め",
        "コックリさん"
    ],
    "series": [],
    "characters": [
        "倉三沢あかね"
    ],
    "suzuri": [
        {
            "title": "こっくり部副部長　倉三沢あかね",
            "url": "https://suzuri.jp/noreal_koma/designs/18351229"
        }
    ],
    "lineSticker": [],
    "instagram": [],
    "QRCode": []
}

=== saasan/noreal-koma-json/202502/noreal_koma-1891797809478893628-01-20250218193200.json
{
    "id": "https://twitter.com/noreal_koma/status/1891797809478893628",
    "publishDate": "2025-02-18T10:32:00+00:00",
    "text": [
        "ありがとうコン子ちゃん！",
        "儂の術……ゴホン 手品にかかればこんなものじゃ！"
    ],
    "reading": [
        "ありがとうこんこちゃん",
        "わしのじゅつごほんてじなにかかればこんなものじゃ"
    ],
    "tag": [
        "巨乳",
        "ふともも",
        "名札"
    ],
    "series": [
        "コンイチ"
    ],
    "characters": [
        "狐鳴紺子郎"
    ],
    "suzuri": [],
    "lineSticker": [],
    "instagram": [
        {
            "title": "Instagram",
            "url": "https://www.instagram.com/noreal_koma/p/DGQJPMySoPX/"
        }
    ],
    "QRCode": []
}

=== saasan/noreal-koma-json/202411/noreal_koma-1861719617108050256-01-20241127193200.json
{
    "id": "https://twitter.com/noreal_koma/status/1861719617108050256",
    "publishDate": "2024-11-27T10:32:00+00:00",
    "text": [
        "手を動かす暇があったら口を動かせ",
        "ヒイ……ッ"
    ],
    "reading": [
        "てをうごかすひまがあったらくちをうごかせ",
        "ひいっ"
    ],
    "tag": [
        "雄っぱい",
        "筋肉"
    ],
    "series": [],
    "characters": [],
    "suzuri": [],
    "lineSticker": [],
    "instagram": [],
    "QRCode": []
}

=== saasan/noreal-koma-json/202507/noreal_koma-1942169722960961927-01-20250707193200.json
{
    "id": "https://twitter.com/noreal_koma/status/1942169722960961927",
    "publishDate": "2025-07-07T10:32:00+00:00",
    "text": [
        "それは流石に家庭環境のせいにしていいと思う。"
    ],
    "reading": [
        "それはさすがにかていかんきょうのせいにしていいとおもう"
    ],
    "tag": [
        "天使",
        "羽",
        "リボン"
    ],
    "series": [],
    "characters": [],
    "suzuri": [],
    "lineSticker": [],
    "instagram": [],
    "QRCode": []
}

=== saasan/noreal-koma-json/202508/noreal_koma-1955215686331994553-01-20250812193200.json
{
    "id": "https://twitter.com/noreal_koma/status/1955215686331994553",
    "publishDate": "2025-08-12T10:32:00+00:00",
    "text": [
        "落ち着いてお並びください！",
        "慌てなくてもブレステ5は逃げませんから！",
        "BS5"
    ],
    "reading": [
        "おちついておならびください",
        "あわてなくてもぶれすてふぁいぶはにげませんから",
        "びーえすふぁいぶ"
    ],
    "tag": [
        "プレステ5",
        "店員",
        "ヒゲ"
    ],
    "series": [],
    "characters": [],
    "suzuri": [],
    "lineSticker": [],
    "instagram": [],
    "QRCode": []
}
